config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  
  root                   'static_pages#home'
  get     'about'     => 'static_pages#about'
  get     'help'      => 'static_pages#help'
  get     'contact'   => 'static_pages#contact'
  get     'signup'    => 'users#new'
  get     'login'     => 'sessions#new'
  post    'login'     => 'sessions#create'
  delete  'logout'    => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :docs
  
  default_url_options :host => "rails-tutorial-shifta.c9.io"

  

end

app/models/doc.rb
class Doc < ActiveRecord::Base
  
  belongs_to :user
  
  default_scope -> { order(created_at: :desc) }
  
  validates :user_id, presence: true
  
  
  has_attached_file :asset, styles: { medium: "300x300>" }
  
  do_not_validate_attachment_file_type :asset
  validates_attachment :asset, presence: true
                               # content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
  
  def s3_credentials
    {:bucket => "istportal-test", :access_key_id => ENV['AWS_ROOT_ACCESS_KEY_ID'], 
    :secret_access_key => ENV['AWS_ROOT_SECRET_ACCESS_KEY'] }
  end
  
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  
  before_action :logged_in_user, only: [:index, :new, :create]
  before_action :correct_user,   only: [:destroy]
  
  
  
  def index
    @user = current_user
    @user_total_size = user_files_size(@user)
    @docs = @user.docs.order('created_at')
    
  end

  def new
    @user = current_user
    @doc = @user.docs.new if logged_in?
  end

  def create
    @user = current_user
    @doc = @user.docs.new(doc_params)
    if @doc.save
      @doc.user_id = @user.id
      flash[:success] = "Your file was added!"
      redirect_to docs_path
    else
      render 'new'
    end
  end
  
  def destroy
    @user = current_user
    @doc = @user.docs.find_by(id: params[:id])
    @doc = nil
    @doc.destroy
    flash[:success] = "File deleted"
    redirect_to request.referrer || docs_path
  end

  private

    def doc_params
      params.require(:doc).permit(:asset, :title)
    end
    
    def correct_user
      @doc = current_user.docs.find_by(id: params[:id])
      redirect_to root_url if @doc.nil?
    end
  
end

app/helpers/docs_helper.rb
module DocsHelper
  
  def user_files_size(user)
    
    user_files = user.docs
    total_size = 0
    if user_files.any?
      user_files.each do |file|
        total_size += file.asset_file_size
      end
      
      return total_size
    else
      return "0"
    end
  end
  
  def uploaded_when(file)
    from_time = file.created_at
    distance_of_time_in_words(from_time, Time.zone.now)
  end
  
end

app/views/docs/_assets.html.erb
<%# Alhamdulillah, for now, the table code is correctly rendering the file
    name and created_at, and the Bootstrap buttons look great. Here's what's 
    left to be done:
    
    (done!) - authenticate this page! Currently, anyone can see the /docs page. Put 
    a filter to authenticate users
    (done!) - ONLY SHOW files that belong to the user who's logged in! Right now,
    any user can see all files uploaded.
    
    - get the download/delete links to work (they look good for now)
    
    (done!)- add an if/else to show something else (ex. "You don't have any files 
    uploaded now!" if there are no files in @user.docs %>

<% if @user && @user == current_user %>
  <div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="col-md-4">File Name</th>
          <th class="col-md-2">Date Uploaded</th>
          <th class="col-md-2">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @user.docs.each do |file| %>
          <tr>
            <td><%= file.title %></td>
            <td><%= uploaded_when(file) %> ago</td>
            <td>
              <%= link_to "Download", file.asset.url, class: "btn btn-primary" %>
              <%= link_to "Delete" , file, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

<% else %>
  <p align="center"><%= current_user.name %>, you don't currently have any files stored in the IST Portal. Click the button below to add a new one!</p>
  <hr />
<% end %>

  

app/views/docs/_doc.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to image_tag(doc.asset.url, class: 'media-object'), doc.asset.url, target: '_blank' %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= doc.title %></h4>
  </div>
</div>

app/views/docs/index.html.erb
<% provide(:title, "#{@user.name}'s Files") %>

<%# Add some code so that if the user has no files, instead of showing an
    
    (done!)empty table, show a message like "You don't currently have any files!"
    
    also, a notice: "cloud storage is (by Allah's will) very safe, but please 
    ensure that your files are backed up somewhere else in case of a disaster!
    
    (done!) finally, add a big "Upload a new file" button somewhere
    
    %>

<h1>Your Files</h1>

<% if @user.docs.any? %>
  <%= render 'assets' %>
<% else %>
  <p>You don't currently have any files in the IST Portal. Add one below!</p>
<% end %>

<div class="text-center">
  <%= link_to "Upload a file", new_doc_path, class: "btn btn-lg btn-primary button-center" %>  
</div>

app/views/docs/new.html.erb
<% provide(:title, "Upload a file") %>
<h1>Upload a File</h1></div>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@doc, html: { multipart: true }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
  
      <%= f.label :asset %>
      <%= f.file_field :asset, placeholder: "pick a file", class: 'form-control'%>
    
      <div class="text-center">
        <%= link_to "Nevermind, go back", docs_path, class: 'btn btn-info' %>
      </div>
      
      <div class="spacer"></div>
      
      <div class="col-md-4 col-md-offset-4">
          <%= f.submit 'Upload', class: 'btn btn-success' %>
      </div>
      
    <% end %>
  </div>
</div>